# docker-compose.yml
version: '3.8'

services:
  # PostgreSQL for local Supabase development
  postgres:
    image: postgres:15-alpine
    container_name: kundenmagnet_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kundenmagnetapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: kundenmagnet_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Mailhog for local email testing
  mailhog:
    image: mailhog/mailhog
    container_name: kundenmagnet_mailhog
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    logging:
      driver: 'none' # Disable excessive logging

volumes:
  postgres_data:
  redis_data:
