name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env.local for build
        run: |
          cat > .env.local << 'EOF'
          # CI Build ENV - Minimal values to pass build
          NEXT_PUBLIC_SUPABASE_URL=https://placeholder.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-anon-key
          SUPABASE_SERVICE_ROLE_KEY=placeholder-service-role-key
          SUPABASE_DB_URL=postgresql://placeholder

          AWS_SES_REGION=eu-central-1
          AWS_ACCESS_KEY_ID=placeholder-key-id
          AWS_SECRET_ACCESS_KEY=placeholder-secret
          SES_FROM="Kundenmagnetapp <no-reply@kundenmagnet-app.de>"
          SES_REPLY_TO=support@kundenmagnet-app.de

          IP_HASH_PEPPER=ci-placeholder-pepper-change-in-production

          STRIPE_SECRET_KEY=sk_test_placeholder
          STRIPE_WEBHOOK_SECRET=whsec_placeholder
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder

          APP_BASE_URL=https://kundenmagnet-app.de

          QR_DEFAULT_COLOR=#000000
          QR_DEFAULT_SIZE=1024
          EOF

      - name: Run TypeScript check
        run: pnpm typecheck

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier check
        run: pnpm format:check

      - name: Build application
        run: pnpm build

      - name: Upload build artifacts (optional)
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          retention-days: 7
